name: Check for new releases of packages that are built from GitHub releases

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  check_for_update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [satstack-bin]
    steps:
    - uses: actions/checkout@v2

    - run: ./check_for_update.sh ${{ matrix.package }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
